### ISSUE TITLE
gridss fails without an active exception

### ISSUE THREAD

**Issue by kalexiou** [PapenfussLab/gridss#428]
Hi,

I am launching the following command with sbatch and gridss exits without an active exception, according to the gridss log, but with an exit code 134, according to slurm. I have attached the log files of gridss and slurm. Any help will be appreciated.

`#SBATCH --cpus-per-task=3`
`#SBATCH --mem-per-cpu=32G`

`singularity run -B /scratch ~/gridss_latest.sif -w gridss_results --output Olea17.vcf.gz -t 3 --reference /scratch/022-fragaria.ananassa-SNPdiscovery/olive/Olea_europaea_chromosome_unplaced_scaffolds.fasta --assembly gridss.assembly.01145_10FN19_A1_1_S5.bam Olea17_genes.bam`

Thanks

[gridss.full.20201112_115133.huberman.3478.log](https://github.com/PapenfussLab/gridss/files/5530096/gridss.full.20201112_115133.huberman.3478.log)
[gridss.timing.20201112_115133.huberman.3478.log](https://github.com/PapenfussLab/gridss/files/5530097/gridss.timing.20201112_115133.huberman.3478.log)
[slurm.txt](https://github.com/PapenfussLab/gridss/files/5530101/slurm.txt)

**Comment by d-cameron** [comment]
It's a JVM crash running the picard metrics calculation. I *think* I fixed this in v2.10.0 as I remember encountering the same issue, but I my git log messages weren't good enough for me to be able to confirm exactly which commit this was fixed in.

Still working on a v2.10 docker image since it's not as simple as updating the jar and scripts since v2.10 introduces C compiled code into GRIDSS as well.

**Comment by kalexiou** [comment]
Hi @d-cameron. The last version available as a docker image is 2.9.4 (https://hub.docker.com/r/gridss/gridss/tags). I have tried version 2.9.1 and still getting the same error. I suppose that we will have to wait for the new version?.
Thanks
